

version: '3'

vars:
  VERSION: v0.5.0
  IMAGE_NAME: europe-docker.pkg.dev/kubemq/images/ibm-mq-connector

tasks:
  default:
    env:
#      LOG_LEVEL: ERROR
    #      CONFIGURATION_FILE_PATH: ./config/config.yaml
    cmds:
      - uv run main.py
  lint:
    cmds:
      - ruff format
      - ruff check --fix

  docker:
    cmds:
      - gcloud config set project kubemq
      - docker buildx build --platform linux/amd64 --load -t {{.IMAGE_NAME}}:{{.VERSION}} . --no-cache --push
      - docker pull {{.IMAGE_NAME}}:{{.VERSION}}
      - docker tag {{.IMAGE_NAME}}:{{.VERSION}} {{.IMAGE_NAME}}:latest
      - docker push {{.IMAGE_NAME}}:latest
      - trivy image --exit-code 1 --severity CRITICAL,HIGH {{.IMAGE_NAME}}:{{.VERSION}}

  docker-push:
    cmds:
      - docker push {{.IMAGE_NAME}}:{{.VERSION}}
  trivy:
    cmds:
      - trivy image --exit-code 1 --severity HIGH,CRITICAL {{.IMAGE_NAME}}:{{.VERSION}}
  #      - trivy image --exit-code 1 --severity HIGH,CRITICAL python:3.13.0-alpine3.20
  docker-run:
    cmds:
      - docker run -it -v ${PWD}/config.yaml:/app/config.yaml {{.IMAGE_NAME}}:{{.VERSION}}
  deploy:
    dir: ./deployment
    cmds:
      - kubectl config use-context gke_ji-portal-v2_us-central1_ai-agent-cluster
      - kubectl apply -k . -n default
  deploy-ibmmq:
    cmds:
      - docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1 --publish 1414:1414 --publish 9443:9443 --detach --env MQ_APP_PASSWORD=passw0rd  ibmcom/mq:latest
