bindings:
  - name: kubemq_to_ibm
    type: kubemq_to_ibm_mq
    source:
      address: host.docker.internal:50000
      queue_name: to_ibm
      client_id: kubemq-client
      poll_interval_seconds: 1
    target:
      host_name: 84.200.100.229
      port_number: 32384
      channel_name: SECUREAPP.CHANNEL
      queue_manager: secureapphelm
      queue_name: SECUREAPP.QUEUE
      username: admin
      password: Passw0rd
      poll_interval_ms: 100

  - name: ibm_to_kubemq
    type: ibm_mq_to_kubemq
    source:
      host_name: 84.200.100.229
      port_number: 32384
      channel_name: SECUREAPP.CHANNEL
      queue_manager: secureapphelm
      queue_name: SECUREAPP.QUEUE
      username: admin
      password: Passw0rd
      poll_interval_ms: 100
    target:
      address: host.docker.internal:50000
      queue_name: from_ibm
      client_id: kubemq-target